# .travis.yml
# This file should be at the root of your project
language: ruby
cache: bundler
gemfile: Gemfile
script:
  - bundle exec jekyll algolia --destination _site --config _config.yml
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - gh-pages
rvm:
  - 2.4
